repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.27
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.27
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.27
  elemental2_webstorage: org.realityforge.com.google.elemental2:elemental2-webstorage:jar:2.27

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0
